/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/patient-register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new patient */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Unique health card number for the patient. */
                        healthCardNumber?: string;
                        /** @description Mobile number of the patient. */
                        mobileNumber?: string;
                        /** @description Email address of the patient. */
                        emailAddress?: string;
                        /** @description Channel for OTP delivery (either 'sms' or 'email'). Default is 'sms'. */
                        otpChannel?: string;
                        /** @description ID of the patient's preferred clinic. */
                        preferredClinicId?: string;
                    };
                };
            };
            responses: {
                /** @description Code sent successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            /** @example Code sent successfully */
                            message?: string;
                            /** @example 3e107006-a770-4349-a2f5-6e4ab266cad3 */
                            patientId?: string;
                        };
                    };
                };
                /** @description Invalid input or patient already exists */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            message?: string;
                            error?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/admin-register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new admin */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description First name of the admin. */
                        firstName?: string;
                        /** @description Last name of the admin. */
                        lastName?: string;
                        /** @description Unique username for the admin. */
                        username?: string;
                        /** @description Mobile number of the admin. */
                        phoneNumber?: string;
                        /** @description Email address of the admin. */
                        email?: string;
                    };
                };
            };
            responses: {
                /** @description Admin registered successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            /** @example Admin registered successfully */
                            message?: string;
                            /** @example 047aede2-edb3-4ab8-8286-39e9f2ef288a */
                            adminId?: string;
                        };
                    };
                };
                /** @description Invalid input or admin already exists */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            message?: string;
                            error?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/admin-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login an admin using username and access code */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Username of the admin */
                        username?: string;
                        /** @description The channel used for OTP delivery (either 'sms' or 'email'). Default is 'sms'. */
                        otpChannel?: string;
                    };
                };
            };
            responses: {
                /** @description Code sent successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            /** @example Code sent successfully */
                            message?: string;
                            /** @example 3e107006-a770-4349-a2f5-6e4ab266cad3 */
                            adminId?: string;
                        };
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            error?: string;
                        };
                    };
                };
                /** @description Invalid credentials (username not found) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example Invalid Credentials */
                            message?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-access-code-admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify access code for an admin */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Username of the admin. */
                        username?: string;
                        /** @description OTP channel (either 'sms' or 'email'). Default is 'sms'. */
                        otpChannel?: string;
                        /** @description Access code sent to the admin. */
                        accessCode?: string;
                    };
                };
            };
            responses: {
                /** @description Access code verified successfully. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            /** @description Admin details. */
                            data?: {
                                /** @example 047aede2-ecb3-4cd8-8286-39e9a1ee288a */
                                id?: string;
                                /** @example admin@example.com */
                                email?: string;
                                /** @example +447367595421 */
                                phone_number?: string;
                                /** @example adminuser */
                                username?: string;
                                /** @example John */
                                first_name?: string;
                                /** @example Doe */
                                last_name?: string;
                                /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
                                access_token?: string;
                                /**
                                 * Format: date-time
                                 * @example 2024-08-23T11:01:40.532Z
                                 */
                                createdAt?: string;
                                /**
                                 * Format: date-time
                                 * @example 2024-08-23T11:01:40.532Z
                                 */
                                updatedAt?: string;
                            };
                        };
                    };
                };
                /** @description Bad request or server error. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example Detailed error message */
                            error?: string;
                        };
                    };
                };
                /** @description Invalid access code. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example Invalid Access Code */
                            message?: string;
                        };
                    };
                };
                /** @description Invalid credentials (admin not found). */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example Invalid Credentials */
                            message?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/patient-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login a patient using health card number and access code */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description The health card number of the patient. */
                        healthCardNumber?: string;
                        /** @description The channel used for OTP delivery (either 'sms' or 'email'). Default is 'sms'. */
                        otpChannel?: string;
                    };
                };
            };
            responses: {
                /** @description Code sent successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            /** @example Code sent successfully */
                            message?: string;
                            /** @example 3e107006-a770-4349-a2f5-6e4ab266cad3 */
                            patientId?: string;
                        };
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            error?: string;
                        };
                    };
                };
                /** @description Invalid credentials (health card number not found) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example Invalid Credentials */
                            message?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/access_code_verification_patient/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify patient access code */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Patient's user ID. */
                    uid: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description The access code provided to the patient. */
                        accessCode?: string;
                        /** @description The channel used for OTP delivery (either 'sms' or 'email'). Default is 'sms'. */
                        otpChannel?: string;
                    };
                };
            };
            responses: {
                /** @description Correct access code */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            /** @description Provider details. */
                            data?: {
                                /** @example 047aede2-ecb3-4cd8-8286-39e9a1ee288a */
                                id?: string;
                                /** @example khalid@example.com */
                                email_address?: string;
                                /** @example +447367595421 */
                                phone_number?: string;
                                /** @example khalid */
                                username?: string;
                                /** @example Walmart Clinic */
                                clinic?: string;
                                /** @example string */
                                access_token?: string;
                                /**
                                 * Format: date-time
                                 * @example 2024-08-23T11:01:40.532Z
                                 */
                                createdAt?: string;
                                /**
                                 * Format: date-time
                                 * @example 2024-08-23T11:01:40.532Z
                                 */
                                updatedAt?: string;
                            };
                        };
                    };
                };
                /** @description Incorrect access code */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example Invalid Access Code */
                            message?: string;
                        };
                    };
                };
                /** @description Invalid credentials */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example Invalid Credentials */
                            message?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/provider-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login a provider using username and access code */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Username of the provider */
                        username?: string;
                        /** @description The channel used for OTP delivery (either 'sms' or 'email'). Default is 'sms'. */
                        otpChannel?: string;
                    };
                };
            };
            responses: {
                /** @description Code sent successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            /** @example Code sent successfully */
                            message?: string;
                        };
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            error?: string;
                        };
                    };
                };
                /** @description Invalid credentials (username not found) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example Invalid Credentials */
                            message?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-verification-code-provider": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify access code for a provider */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Username of the provider. */
                        username?: string;
                        /** @description otp channel */
                        otpChannel?: string;
                        /** @description Access code sent to the provider. */
                        accessCode?: string;
                    };
                };
            };
            responses: {
                /** @description Access code verified successfully. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            /** @description Provider details. */
                            data?: {
                                /** @example 047aede2-ecb3-4cd8-8286-39e9a1ee288a */
                                id?: string;
                                /** @example khalid@example.com */
                                email_address?: string;
                                /** @example +447367595421 */
                                phone_number?: string;
                                /** @example khalid */
                                username?: string;
                                /** @example Walmart Clinic */
                                clinic?: string;
                                /** @example string */
                                access_token?: string;
                                /**
                                 * Format: date-time
                                 * @example 2024-08-23T11:01:40.532Z
                                 */
                                createdAt?: string;
                                /**
                                 * Format: date-time
                                 * @example 2024-08-23T11:01:40.532Z
                                 */
                                updatedAt?: string;
                            };
                        };
                    };
                };
                /** @description Bad request or server error. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example Detailed error message */
                            error?: string;
                        };
                    };
                };
                /** @description Invalid access code. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example Invalid Access Code */
                            message?: string;
                        };
                    };
                };
                /** @description Invalid credentials (provider not found). */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example Invalid Credentials */
                            message?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/get-ms-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve Microsoft access token */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Microsoft access token retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description The Microsoft access token.
                             * @example eyJ0eXAiOiJKV1QiLCJhb...
                             */
                            msAccessToken?: string;
                            /**
                             * @description Token expiration time in seconds.
                             * @example 3600
                             */
                            expires_in?: number;
                        };
                    };
                };
                /** @description Error retrieving token */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Error message
                             * @example Invalid client credentials
                             */
                            error?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clinics/get-all-clinics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve a list of clinics with their services */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A list of clinics with their associated services */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 1a2b3c4d */
                            id?: string;
                            /** @example 4d33d464-e2d0-4abf-b216-5551b0496505 */
                            medical_group_id?: string;
                            /** @example Health Clinic */
                            name?: string;
                            /** @example 123 Health St. */
                            location?: string;
                            /** @example 9 AM - 5 PM */
                            weekday_hours?: string;
                            /** @example 10 AM - 4 PM */
                            weekend_hours?: string;
                            /** @example +123456789 */
                            contact?: string;
                            /** @example active */
                            status?: string;
                            services?: {
                                /** @example s1a2b3c4 */
                                id?: string;
                                /** @example General Check-up */
                                name?: string;
                            }[];
                        }[];
                    };
                };
                /** @description Error retrieving clinics */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Error message */
                            error?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clinics/create-clinic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new clinic */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example 047aede2-edb3-4ab8-8286-39e9f2ef288a */
                        medical_group_id?: string;
                        /** @example Health Clinic */
                        name?: string;
                        /** @example 123 Health St. */
                        location?: string;
                        /** @example 9 AM - 5 PM */
                        weekday_hours?: string;
                        /** @example 10 AM - 4 PM */
                        weekend_hours?: string;
                        /** @example +123456789 */
                        contact?: string;
                        /** @example active */
                        status?: string;
                    };
                };
            };
            responses: {
                /** @description Clinic created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 1a2b3c4d */
                            id?: string;
                            /** @example 047aede2-edb3-4ab8-8286-39e9f2ef288a */
                            medical_group_id?: string;
                            /** @example Health Clinic */
                            name?: string;
                            /** @example 123 Health St. */
                            location?: string;
                            /** @example 9 AM - 5 PM */
                            weekday_hours?: string;
                            /** @example 10 AM - 4 PM */
                            weekend_hours?: string;
                            /** @example +123456789 */
                            contact?: string;
                            /** @example active */
                            status?: string;
                        };
                    };
                };
                /** @description Validation error for the input data */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Medical group ID and name are required. */
                            error?: string;
                        };
                    };
                };
                /** @description Error creating clinic */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Error creating clinic */
                            error?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients/waiting-list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve the list of patients in the waiting list
         * @description Fetch all patients who are not registered and are on the waiting list.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully retrieved the waiting list patients */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Indicates whether the request was successful
                             * @example true
                             */
                            success?: boolean;
                            /**
                             * @description Message indicating the success of the operation
                             * @example Waiting list patients retrieved successfully
                             */
                            message?: string;
                            data?: {
                                /**
                                 * Format: uuid
                                 * @description The unique ID of the patient
                                 * @example b6f632a3-d4f9-4ad8-b7ad-3d431ff890d7
                                 */
                                id?: string;
                                /**
                                 * @description The first name of the patient
                                 * @example John
                                 */
                                first_name?: string;
                                /**
                                 * @description The last name of the patient
                                 * @example Doe
                                 */
                                last_name?: string;
                                /**
                                 * @description The phone number of the patient
                                 * @example 123-456-7890
                                 */
                                phone_number?: string;
                                /**
                                 * @description The email address of the patient
                                 * @example john.doe@example.com
                                 */
                                email_address?: string;
                                /**
                                 * Format: date
                                 * @description The date of birth of the patient
                                 * @example 1980-01-01
                                 */
                                date_of_birth?: string;
                                /**
                                 * @description The name of the preferred clinic of the patient
                                 * @example Hope Health Center
                                 */
                                preferred_clinic?: string;
                                /**
                                 * @description Whether the patient is registered or not
                                 * @example false
                                 */
                                registered?: boolean;
                                /**
                                 * Format: date-time
                                 * @description The creation date of the patient record
                                 * @example 2024-10-18T12:00:00Z
                                 */
                                createdAt?: string;
                                /**
                                 * @description The type of preferred provider for the patient
                                 * @example Family physician
                                 */
                                preferred_provider?: string;
                            }[];
                        };
                    };
                };
                /** @description An error occurred while fetching waiting list patients */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Indicates whether the request was successful
                             * @example false
                             */
                            success?: boolean;
                            /**
                             * @description Error message
                             * @example An error occurred while fetching waiting list patients
                             */
                            message?: string;
                            /**
                             * @description Error details
                             * @example Database connection error
                             */
                            error?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients/patient-update/{health_card_number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update a Patients Details
         * @description Update the patient details using the health card number.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The health card number of the patient */
                    health_card_number: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully updated the patient details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: uuid
                             * @description The unique ID of the patient
                             * @example b6f632a3-d4f9-4ad8-b7ad-3d431ff890d7
                             */
                            id?: string;
                            /**
                             * @description The first name of the patient
                             * @example John
                             */
                            first_name?: string;
                            /**
                             * @description The last name of the patient
                             * @example Doe
                             */
                            last_name?: string;
                            /**
                             * @description The health card number of the patient
                             * @example 123456789
                             */
                            health_card_number?: string;
                            /**
                             * @description The email address of the patient
                             * @example john.doe@example.com
                             */
                            email_address?: string;
                            /**
                             * @description The phone number of the patient
                             * @example 123-456-7890
                             */
                            phone_number?: string;
                            /**
                             * @description The sex of the patient
                             * @example Male
                             */
                            sex?: string;
                            /**
                             * @description The pronouns of the patient
                             * @example He/Him
                             */
                            pronouns?: string;
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Error message
                             * @example Error updating patient data
                             */
                            error?: string;
                        };
                    };
                };
                /** @description Patient not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Error message
                             * @example Patient not found
                             */
                            error?: string;
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new provider */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /**
                         * @description First name of the provider
                         * @example John
                         */
                        first_name?: string;
                        /**
                         * @description Last name of the provider
                         * @example Doe
                         */
                        last_name?: string;
                        /**
                         * @description Unique username for the provider
                         * @example john_doe
                         */
                        username?: string;
                        /**
                         * @description Medical Council Number of the provider
                         * @example 300558123
                         */
                        mnc_number?: string;
                        /**
                         * @description Provider's phone number
                         * @example +1234567890
                         */
                        phone_number?: string;
                        /**
                         * @description Provider's email address
                         * @example johndoe@example.com
                         */
                        email_address?: string;
                        /**
                         * @description Type of provider (e.g., family-physician, surgeon, etc.)
                         * @example family-physician
                         */
                        provider_type?: string;
                        /**
                         * @description Status of the provider (e.g., available, unavailable)
                         * @example available
                         */
                        provider_status?: string;
                        /**
                         * Format: binary
                         * @description Provider's picture (image file)
                         */
                        picture?: string;
                    };
                };
            };
            responses: {
                /** @description Provider created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            /** @example Provider created successfully */
                            message?: string;
                            provider?: {
                                /** @example 047aede2-ecb3-4cd8-8286-39e9a1ee288a */
                                id?: string;
                                /** @example John */
                                first_name?: string;
                                /** @example Doe */
                                last_name?: string;
                                /** @example john_doe */
                                username?: string;
                                /** @example 300558123 */
                                mnc_number?: string;
                                /** @example +1234567890 */
                                phone_number?: string;
                                /** @example johndoe@example.com */
                                email_address?: string;
                                /** @example family-physician */
                                provider_type?: string;
                                /** @example available */
                                provider_status?: string;
                                /** @example https://res.cloudinary.com/provider_images/sample.jpg */
                                picture?: string;
                            };
                        };
                    };
                };
                /** @description Error creating provider due to invalid request data */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example Please provide all required fields */
                            message?: string;
                        };
                    };
                };
                /** @description Server error while creating the provider */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example An error occurred while creating the provider */
                            message?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update an existing provider */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The ID of the provider to update */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** @example John */
                        first_name?: string;
                        /** @example Doe */
                        last_name?: string;
                        /** @example john_doe */
                        username?: string;
                        /** @example 300558123 */
                        mnc_number?: string;
                        /** @example +1234567890 */
                        phone_number?: string;
                        /** @example johndoe@example.com */
                        email_address?: string;
                        /** @example family-physician */
                        provider_type?: string;
                        /** @example available */
                        provider_status?: string;
                        /**
                         * Format: binary
                         * @description Updated provider's picture
                         */
                        picture?: string;
                    };
                };
            };
            responses: {
                /** @description Provider updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            /** @example Provider updated successfully */
                            message?: string;
                            provider?: {
                                /** @example 047aede2-ecb3-4cd8-8286-39e9a1ee288a */
                                id?: string;
                                /** @example John */
                                first_name?: string;
                                /** @example Doe */
                                last_name?: string;
                                /** @example john_doe */
                                username?: string;
                                /** @example 300558123 */
                                mnc_number?: string;
                                /** @example +1234567890 */
                                phone_number?: string;
                                /** @example johndoe@example.com */
                                email_address?: string;
                                /** @example family-physician */
                                provider_type?: string;
                                /** @example available */
                                provider_status?: string;
                                /** @example https://res.cloudinary.com/provider_images/sample.jpg */
                                picture?: string;
                            };
                        };
                    };
                };
                /** @description Error updating provider */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example Validation error */
                            message?: string;
                        };
                    };
                };
                /** @description Provider not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example Provider not found */
                            message?: string;
                        };
                    };
                };
                /** @description Server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example An error occurred while updating the provider */
                            message?: string;
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/get-all-providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve a list of providers with their details */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A list of providers with their details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 047aede2-ecb3-4cd8-8286-39e9a1ee288a */
                            id?: string;
                            /** @example Lanre */
                            first_name?: string;
                            /** @example Egbeyemi */
                            last_name?: string;
                            /** @example lanre_egbeyemi */
                            user_name?: string;
                            /** @example https://storage-api.pgrninc.com/internal-dashboard/111225.png */
                            picture?: string;
                            /** @example Family physician */
                            provider_type?: string;
                            /** @example Available */
                            provider_status?: string;
                            /** @example 4 */
                            patient_count?: number;
                        }[];
                    };
                };
                /** @description Error retrieving providers */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example An error occurred while fetching providers */
                            error?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/{providerId}/patients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve a list of patients for a specific provider */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The ID of the provider to retrieve patients for */
                    providerId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A provider and their list of associated patients */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Maya */
                            provider_first_name?: string;
                            /** @example Tandie */
                            provider_last_name?: string;
                            /** @example tandie_maya */
                            provider_username?: string;
                            patients?: {
                                /** @example 047aede2-edb3-4da8-8286-39e9f2ee2128 */
                                id?: string;
                                /** @example Olanrewaju */
                                first_name?: string;
                                /** @example Egbeyemi */
                                last_name?: string;
                                /** @example Male */
                                sex?: string;
                                /** @example larrichy@hotmail.com */
                                email_address?: string;
                                /** @example 420709096 */
                                health_card_number?: string;
                                /** @example +13069606702 */
                                phone_number?: string;
                                /** @example 56 years */
                                age?: string;
                                /** @example Walmart Clinic */
                                clinic_name?: string;
                                /** @example 5 sep,2024 */
                                next_appointment_date?: string;
                            }[];
                        };
                    };
                };
                /** @description Provider not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Provider not found */
                            error?: string;
                        };
                    };
                };
                /** @description Error retrieving patients */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Error message */
                            error?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/{providerId}/assign-patients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assign multiple patients to a provider */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID of the provider to whom patients will be assigned */
                    providerId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description Array of patient IDs to be assigned to the provider
                         * @example [
                         *       "5fae1b5c6f8b3c0017e4a234",
                         *       "5fae1b5c6f8b3c0017e4a235"
                         *     ]
                         */
                        patientIds?: string[];
                    };
                };
            };
            responses: {
                /** @description Patients successfully assigned to the provider */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            /** @example Patients successfully assigned to the provider */
                            message?: string;
                            assignments?: {
                                /** @example 5fae1b5c6f8b3c0017e4a234 */
                                patient_id?: string;
                                /** @example 5fae1b5c6f8b3c0017e4a123 */
                                provider_id?: string;
                            }[];
                        };
                    };
                };
                /** @description Invalid input, such as missing or incorrect patient IDs */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example Please provide valid patient IDs */
                            message?: string;
                        };
                    };
                };
                /** @description Provider or one of the patients not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example Provider not found */
                            message?: string;
                        };
                    };
                };
                /** @description Server error occurred while assigning patients to the provider */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example An error occurred while assigning patients to the provider */
                            message?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/provider-update/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update a provider's basic information */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The ID of the provider to update */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** @example John */
                        first_name?: string;
                        /** @example Doe */
                        last_name?: string;
                        /** @example +1234567890 */
                        phone_number?: string;
                        /** @example johndoe@example.com */
                        email_address?: string;
                        /**
                         * Format: binary
                         * @description Updated provider's picture
                         */
                        picture?: string;
                        /** @description Array of clinic IDs to associate with the provider */
                        clinics?: string[];
                    };
                };
            };
            responses: {
                /** @description Provider updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            /** @example Provider updated successfully */
                            message?: string;
                            provider?: {
                                /** @example 047aede2-ecb3-4cd8-8286-39e9a1ee288a */
                                id?: string;
                                /** @example John */
                                first_name?: string;
                                /** @example Doe */
                                last_name?: string;
                                /** @example +1234567890 */
                                phone_number?: string;
                                /** @example johndoe@example.com */
                                email_address?: string;
                                /** @example https://res.cloudinary.com/provider_images/sample.jpg */
                                picture?: string;
                                /** @example [
                                 *       "047aede2-ecb3-4cd8-8286-39e9a1ee288a",
                                 *       "1234abcd-56ef-78gh-90ij-klmnopqrstuv"
                                 *     ] */
                                clinics?: string[];
                            };
                        };
                    };
                };
                /** @description Error updating provider */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example Validation error */
                            message?: string;
                        };
                    };
                };
                /** @description Provider not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example Provider not found */
                            message?: string;
                        };
                    };
                };
                /** @description Server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example An error occurred while updating the provider */
                            message?: string;
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/provider/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve a provider's detailed information */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The ID of the provider to retrieve information for */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Provider information retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            provider?: {
                                /** @example 047aede2-ecb3-4cd8-8286-39e9a1ee288a */
                                id?: string;
                                /** @example John */
                                first_name?: string;
                                /** @example Doe */
                                last_name?: string;
                                /** @example johndoe@example.com */
                                email_address?: string;
                                /** @example +1234567890 */
                                phone_number?: string;
                                /** @example https://res.cloudinary.com/provider_images/sample.jpg */
                                picture?: string;
                                /** @example johndoe */
                                username?: string;
                                /** @example [
                                 *       "chiropractor"
                                 *     ] */
                                provider_type?: string[];
                                clinics?: {
                                    /** @example 047aede2-edb3-4ab8-8286-39e9f2ef288a */
                                    id?: string;
                                    /** @example Hope Health Center */
                                    name?: string;
                                    /** @example 1135 Central Avenue Prince Albert, SK S6V 4V7 */
                                    location?: string;
                                    /** @example 8:00 AM - 6:00 PM */
                                    weekday_hours?: string;
                                    /** @example 9:00 AM - 4:00 PM */
                                    weekend_hours?: string;
                                    /** @example 555-1234 */
                                    contact?: string;
                                    /** @example active */
                                    status?: string;
                                    /** @example null */
                                    ms_calendar_id?: string | null;
                                    medicalGroup?: {
                                        /** @example 047aede2-edb3-4ab8-8286-39e9f2ef288a */
                                        id?: string;
                                        /** @example PACMC */
                                        name?: string;
                                        /** @example null */
                                        status?: string | null;
                                        /** @example pacmc */
                                        info?: string;
                                        /** @example null */
                                        validity_date?: string | null;
                                    };
                                }[];
                            };
                        };
                    };
                };
                /** @description Provider not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example Provider not found */
                            message?: string;
                        };
                    };
                };
                /** @description Server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example An error occurred while retrieving the provider information */
                            message?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
